// File generated by FlutterFire CLI.
// Contains configuration for Firebase initialization

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can create a web app in the Firebase console.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can create a macOS app in the Firebase console.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can create a Windows app in the Firebase console.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can create a Linux app in the Firebase console.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Catatan: Anda perlu mengganti nilai-nilai berikut dengan konfigurasi Firebase Anda sendiri
  // yang didapatkan dari Firebase Console setelah membuat project
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaObHVLfURnM1L7ZsEGVIv8HCKoVhYYnQ',
    appId: '1:937137485690:android:457a6c7f0d80b82956c8c3',
    messagingSenderId: '937137485690',
    projectId: 'yaumian-app',
    storageBucket: 'yaumian-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqiUOfcqnLvkCzm2EWCv3xrqSrTuqBaqc',
    appId: '1:937137485690:ios:0564e82c8b90c13256c8c3',
    messagingSenderId: '937137485690',
    projectId: 'yaumian-app',
    storageBucket: 'yaumian-app.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.yaumian.yaumianApp',
  );
}
